"""Initial migration

Revision ID: aef7d233b9f9
Revises: 
Create Date: 2026-03-24 20:11:35.858984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef7d233b9f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyweight_log',
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bodyweight_log'))
    )
    op.create_table('exercise',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise')),
    sa.UniqueConstraint('name', name=op.f('uq_exercise_name'))
    )
    op.create_table('mesocycle',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='mesocyclestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mesocycle'))
    )
    op.create_table('muscle_group',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_muscle_group')),
    sa.UniqueConstraint('name', name=op.f('uq_muscle_group_name'))
    )
    op.create_table('routine',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine'))
    )
    op.create_table('exercise_muscle_group',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('muscle_group_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'SECONDARY', name='musclerole'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_muscle_group_exercise_id_exercise'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_group.id'], name=op.f('fk_exercise_muscle_group_muscle_group_id_muscle_group')),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id', name=op.f('pk_exercise_muscle_group'))
    )
    op.create_table('mesocycle_week',
    sa.Column('mesocycle_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.Enum('TRAINING', 'DELOAD', name='weektype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycle.id'], name=op.f('fk_mesocycle_week_mesocycle_id_mesocycle'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mesocycle_week')),
    sa.UniqueConstraint('mesocycle_id', 'week_number', name=op.f('uq_mesocycle_week_mesocycle_id'))
    )
    op.create_table('routine_exercise',
    sa.Column('routine_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_routine_exercise_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_routine_exercise_routine_id_routine'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_exercise')),
    sa.UniqueConstraint('routine_id', 'order', name=op.f('uq_routine_exercise_routine_id'))
    )
    op.create_table('planned_session',
    sa.Column('mesocycle_week_id', sa.Uuid(), nullable=False),
    sa.Column('routine_id', sa.Uuid(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mesocycle_week_id'], ['mesocycle_week.id'], name=op.f('fk_planned_session_mesocycle_week_id_mesocycle_week'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_planned_session_routine_id_routine')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_session')),
    sa.UniqueConstraint('mesocycle_week_id', 'date', name=op.f('uq_planned_session_mesocycle_week_id'))
    )
    op.create_table('routine_set',
    sa.Column('routine_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.Enum('STANDARD', 'DROPSET', name='settype'), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.Column('target_rir', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('weight_reduction_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercise.id'], name=op.f('fk_routine_set_routine_exercise_id_routine_exercise'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_set')),
    sa.UniqueConstraint('routine_exercise_id', 'set_number', name=op.f('uq_routine_set_routine_exercise_id'))
    )
    op.create_table('session',
    sa.Column('planned_session_id', sa.Uuid(), nullable=True),
    sa.Column('mesocycle_id', sa.Uuid(), nullable=True),
    sa.Column('routine_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycle.id'], name=op.f('fk_session_mesocycle_id_mesocycle')),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_session.id'], name=op.f('fk_session_planned_session_id_planned_session')),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_session_routine_id_routine')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_table('session_exercise',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_session_exercise_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_session_exercise_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_exercise')),
    sa.UniqueConstraint('session_id', 'order', name=op.f('uq_session_exercise_session_id'))
    )
    op.create_table('session_set',
    sa.Column('session_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.Enum('STANDARD', 'DROPSET', name='settype'), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_rir', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_rir', sa.Integer(), nullable=True),
    sa.Column('actual_weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('weight_reduction_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercise.id'], name=op.f('fk_session_set_session_exercise_id_session_exercise'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_set')),
    sa.UniqueConstraint('session_exercise_id', 'set_number', name=op.f('uq_session_set_session_exercise_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_set')
    op.drop_table('session_exercise')
    op.drop_table('session')
    op.drop_table('routine_set')
    op.drop_table('planned_session')
    op.drop_table('routine_exercise')
    op.drop_table('mesocycle_week')
    op.drop_table('exercise_muscle_group')
    op.drop_table('routine')
    op.drop_table('muscle_group')
    op.drop_table('mesocycle')
    op.drop_table('exercise')
    op.drop_table('bodyweight_log')
    # ### end Alembic commands ###
