from typing import Protocol

from app.domain.entities.routine import Routine
from app.domain.repositories.base import BaseRepository


class RoutineRepository(BaseRepository[Routine], Protocol):
    async def count_total(self) -> int: ...

    async def get_exercise_by_id(self, id: UUID) -> RoutineExercise | None: ...

    async def delete_exercise(self, id: UUID) -> bool: ...

    async def get_set_by_id(self, id: UUID) -> RoutineSet | None: ...

    async def delete_set(self, id: UUID) -> bool: ...
