name: API Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Tell GitHub all commands happen inside the api folder
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Speeds up future runs

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Run Tests
        # This calls 'uv run pytest' as defined in your Makefile
        run: make test
